observation_budget: 10
method: bayes
metric:
  name: pixel_AUROC
  goal: maximize
parameters:
  dataset:
    category: capsule
    transform_config:
        train:
          Resize:
            height: 256
            width: 256
          HorizontalFlip:
            p:
              values: [0, 0.5]
          VerticalFlip:
            p:
              values: [0, 0.5]
          RandomBrightnessContrast:
            p: 0
          ShiftScaleRotate:
            p: 0
          ToGray:
            p:
              values: [0, 1.0]
          Blur:
            blur_limit:
              values: [[3,3], [5,5]]
            always_apply: true
            p: 
              values: [0, 1]